CREATE DATABASE chatapp;
\c chatapp;
CREATE TABLE auth (
    ID SERIAL,
    F_NAME  CHAR(50) NOT NULL,
    L_NAME  CHAR(50) NOT NULL,
    EMAIL   CHAR(100) NOT NULL PRIMARY KEY,
    PASSWORD    CHAR(64) NOT NULL
);